# Generated by Django 5.1.5 on 2026-08-20 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, help_text='Lo calcula el endpoint calculate-price; nace vacío.', max_digits=14, null=True)),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=120)),
                ('supplier_country', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['category'], name='books_book_categor_d1abc8_idx'), models.Index(fields=['stock_quantity'], name='books_book_stock_q_728615_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_usd__gt', 0)), name='book_cost_usd_positive'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='book_stock_quantity_not_negative')],
            },
        ),
    ]
